name: Test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    schedule:
        - cron: 0 3 * * 1,3,5
    workflow_dispatch:

env:
    COMPOSER_MEMORY_LIMIT: -1

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 8.1, 8.2, 8.3 ]
            fail-fast: false
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
            -   name: Install dependencies
                run: composer update
            -   name: Run static analysis test suite
                run: composer run test
